### ISSUE TITLE
Underestimated max bed temp

### ISSUE THREAD

**Issue by vegeta340** [klack/LuxuriMarlin#1]
Hi All, I recently updated Tenlog D3 pro software for the newest version from 2 years old build. Everything works fine except settings for bed temp, I was able to go up to 110 celsius degrees and now I am able to go only up to 80 degrees. I have isolated bed and additional fans inside housing, it was never a problem to heat the bed for abs printing. I use T3D Pro with 8 bit MB, TMC2209, titan extruders, optical endstops and without BL sensor. Please help.

**Comment by klack** [comment]
Fixed!
